---
- name: Deploy Nginx Pod
  hosts: all
  become: true

  tasks:
    - name: Create Nginx Pod
      k8s:
        state: "present"
        definition:
          apiVersion: v1
          kind: Pod
          metadata:
            name: nginx-pod
          spec:
            containers:
              - name: nginx-container
                image: nginx:latest
